#!/bin/sh

if [ -z "$LAN" ] || [ -z "$WAN" ]
then
    echo "Usage: LAN=eth0 WAN=wlan0 $0" 1>&2
    echo "you must define LAN and WAN interfaces first!" 1>&2
    exit 1
fi

# Flush all the rules in filter and nat tables
iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain

# Enable NAT
iptables --table nat --append POSTROUTING --out-interface "$WAN" -j MASQUERADE
iptables --append FORWARD --in-interface "$LAN" -j ACCEPT
echo 1 > /proc/sys/net/ipv4/ip_forward
