#!/bin/sh

set -e

METARELEASE=meta-release
METARELEASE_LTS=meta-release-lts
SERVER=changelogs.ubuntu.com
VAR=/var/spool/apt-mirror/var
MIRROR=/var/spool/apt-mirror/mirror/changelogs.ubuntu.com
WGET="wget -q"

if [ $(whoami) != "apt-mirror" ]
then
    echo "$0: must be user apt-mirror" 1>&2
    exit 1
fi

# mirror changelogs server home
cd $MIRROR
${WGET} ${SERVER}/${METARELEASE} && ${WGET} ${SERVER}/${METARELEASE_LTS}